In [130]:
import numpy as np
import matplotlib.pyplot as plt

# Initialization

In [116]:
#Vectors

a = np.zeros(1)
print(a)


[0.]


In [115]:
b = np.zeros(4)
print(b)

[0. 0. 0. 0.]


In [118]:
c =np.zeros((4,1)) #4 rows and 1 column
print(c)

[[0.]
 [0.]
 [0.]
 [0.]]


In [124]:
m =10 
n =10  
# m,n =10,10  Another way of definition
d = np.zeros((m,n)) 
print(d)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [126]:
print(type(d))

<class 'numpy.ndarray'>


In [128]:
#repeat the same for ones as well just like zeros
b = np.ones((4,3,2,3),dtype = int)
print(b)

In [5]:
lst = [91,2,3,45]
# what is a list ? what problem does it solve and advantage ?
a = np.array(lst,ndmin = 3)
print('a = {}' .format(a))
b = np.array(np.mat('2 3 ; 4 6'))
print('b = {}' .format(b))
c = np.array([(1,2,3),(4,5,6),(4,5,5)])
print('c = {}' .format(c))
d = np.array([(1,3+2j,4) ,(3,4,5)],dtype =complex) 
print('d = {}'.format(d))
print(type(d))

a = [[[91  2  3 45]]]
b = [[2 3]
 [4 6]]
c = [[1 2 3]
 [4 5 6]
 [4 5 5]]
d = [[1.+0.j 3.+2.j 4.+0.j]
 [3.+0.j 4.+0.j 5.+0.j]]
<class 'numpy.ndarray'>


# Generate random numeric values

In [141]:
dir(plt)

['Annotation',
 'Arrow',
 'Artist',
 'AutoLocator',
 'Axes',
 'Button',
 'Circle',
 'Figure',
 'FigureCanvasBase',
 'FixedFormatter',
 'FixedLocator',
 'FormatStrFormatter',
 'Formatter',
 'FuncFormatter',
 'GridSpec',
 'IndexLocator',
 'Line2D',
 'LinearLocator',
 'Locator',
 'LogFormatter',
 'LogFormatterExponent',
 'LogFormatterMathtext',
 'LogLocator',
 'MaxNLocator',
 'MultipleLocator',
 'Normalize',
 'NullFormatter',
 'NullLocator',
 'Number',
 'PolarAxes',
 'Polygon',
 'Rectangle',
 'ScalarFormatter',
 'Slider',
 'Subplot',
 'SubplotTool',
 'Text',
 'TickHelper',
 'Widget',
 '_INSTALL_FIG_OBSERVER',
 '_IP_REGISTERED',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 '_auto_draw_if_interactive',
 '_backend_mod',
 '_get_running_interactive_framework',
 '_interactive_bk',
 '_log',
 '_pylab_helpers',
 '_setp',
 '_setup_pyplot_info_docstrings',
 '_show',
 'acorr',
 'angle_spectrum',
 'annotate',
 'arrow',
 'autoscale',

In [146]:

np.random.seed(42)
# np.random.randn(1,1000)
# a = np.random.randn(1,100)
# plt.hist(a,bins = 20) # Gaussian distribution plot
# plt.show()
# print(type(a))
# b = np.random.standard_normal((2,3))
# print((b))


mu, sigma = 100, 15
x = mu + sigma * np.random.randn(10000)
hist, bins = np.histogram(x, bins=50)
width = 0.7 * (bins[1] - bins[0])
center = (bins[:-1] + bins[1:]) / 2
plt.bar(center, hist, align='center', width=width)
plt.show()

plt.plot(x)
plt.show()

In [137]:
data = np.random.randint(2,10,5)
print(data)

[4 6 4 3 4]


# Reshaping matrix

In [8]:
a = np.arange(5,25)
# arange will take 3rd parameter as step(spacing) between first two parameters, 
#  but randint will take 3rd parameter as size (how many numbers you need)
print(a)
print(a.shape)
a = a.reshape(5,2,2)
a


[ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
(20,)


array([[[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16]],

       [[17, 18],
        [19, 20]],

       [[21, 22],
        [23, 24]]])

In [9]:
print(a.shape)
print(a.ndim)
print(a.dtype)
print(a.itemsize)
print(a.size) #no.of elements

(5, 2, 2)
3
int32
4
20


# Basic operations

In [10]:
a = np.array([20,30,40,50])
b = np.arange(4,8)
print(a)
print(b)
c = a.reshape(2,2)
print(c)
print(a-b)
print(b**2)

[20 30 40 50]
[4 5 6 7]
[[20 30]
 [40 50]]
[16 25 34 43]
[16 25 36 49]


In [11]:
np.sin(a)

array([ 0.91294525, -0.98803162,  0.74511316, -0.26237485])

In [12]:
np.sin(np.array((0., 30., 45., 60., 90.)) * np.pi / 180. )

array([0.        , 0.5       , 0.70710678, 0.8660254 , 1.        ])

In [13]:
np.cos(np.array((0.,30.,45.,60.,90.))* np.pi / 180.)

array([1.00000000e+00, 8.66025404e-01, 7.07106781e-01, 5.00000000e-01,
       6.12323400e-17])

In [14]:
print(a[a>45])

[50]


In [15]:
A = np.array( [[1,1], [0,1]] )
B = np.array( [[2,0], [3,4]] )
print (A)
print (B)

# elementwise matrix multiplication
print ("elementwise")
print (A*B)

# matrix product
print ("matrixproduct")
print (A@B)

# another way of matrix product

print (A.dot(B))

[[1 1]
 [0 1]]
[[2 0]
 [3 4]]
elementwise
[[2 0]
 [0 4]]
matrixproduct
[[5 4]
 [3 4]]
[[5 4]
 [3 4]]


# Unary Operations

In [16]:
a = np.random.random((2,3))
a
print(a.shape)
a.sum()
a.min()
a.max()

(2, 3)


0.9818408883105311

In [17]:
b = np.arange(12).reshape(4,3)
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [18]:
b.shape

(4, 3)

In [19]:
b.sum(axis = 0)

array([18, 22, 26])

In [20]:
b.sum(axis =1)

array([ 3, 12, 21, 30])

In [21]:
b.min(axis=0)

array([0, 1, 2])

In [22]:
b.cumsum(axis=0)

array([[ 0,  1,  2],
       [ 3,  5,  7],
       [ 9, 12, 15],
       [18, 22, 26]], dtype=int32)

In [23]:
d = np.array([1,2,3,4,0.5,0.25])
print(d)
np.exp(d)
np.sqrt(d)


[1.   2.   3.   4.   0.5  0.25]


array([1.        , 1.41421356, 1.73205081, 2.        , 0.70710678,
       0.5       ])

In [24]:
np.add(A,B)

array([[3, 1],
       [3, 5]])

# Indexing and Slicing

In [25]:
a =np.arange(10)**2
a

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [26]:
a[6]

36

In [27]:
a[2:5]

array([ 4,  9, 16], dtype=int32)

In [28]:
for i in a :
    print(i**3)

0
1
64
729
4096
15625
46656
117649
262144
531441


In [29]:
b = np.arange(5,15).reshape(2,5)
b

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [30]:
b[0,1]

6

In [31]:
b[:,1]

array([ 6, 11])

In [32]:
 b[1,:]

array([10, 11, 12, 13, 14])

# Shape Manuplation

In [33]:
A = np.floor(10*np.random.random((3,4)))
A

array([[2., 0., 3., 5.],
       [3., 8., 2., 9.],
       [4., 8., 1., 4.]])

In [34]:
A.shape

(3, 4)

In [35]:
A.ravel()

array([2., 0., 3., 5., 3., 8., 2., 9., 4., 8., 1., 4.])

In [36]:
A=A.reshape(6,2)
A


array([[2., 0.],
       [3., 5.],
       [3., 8.],
       [2., 9.],
       [4., 8.],
       [1., 4.]])

In [37]:
A.T

array([[2., 3., 3., 2., 4., 1.],
       [0., 5., 8., 9., 8., 4.]])

In [38]:
A.T.shape

(2, 6)

In [39]:
my_arr = np.arange(1,122).reshape(11,11)
count = 0
for row in my_arr:
    row[count+1:] = 0
    count += 1
print(my_arr)

[[  1   0   0   0   0   0   0   0   0   0   0]
 [ 12  13   0   0   0   0   0   0   0   0   0]
 [ 23  24  25   0   0   0   0   0   0   0   0]
 [ 34  35  36  37   0   0   0   0   0   0   0]
 [ 45  46  47  48  49   0   0   0   0   0   0]
 [ 56  57  58  59  60  61   0   0   0   0   0]
 [ 67  68  69  70  71  72  73   0   0   0   0]
 [ 78  79  80  81  82  83  84  85   0   0   0]
 [ 89  90  91  92  93  94  95  96  97   0   0]
 [100 101 102 103 104 105 106 107 108 109   0]
 [111 112 113 114 115 116 117 118 119 120 121]]


In [40]:
arr = np.arange(1,122).reshape(11,11)
arr[4:9,3:8] = 0
print(arr)

[[  1   2   3   4   5   6   7   8   9  10  11]
 [ 12  13  14  15  16  17  18  19  20  21  22]
 [ 23  24  25  26  27  28  29  30  31  32  33]
 [ 34  35  36  37  38  39  40  41  42  43  44]
 [ 45  46  47   0   0   0   0   0  53  54  55]
 [ 56  57  58   0   0   0   0   0  64  65  66]
 [ 67  68  69   0   0   0   0   0  75  76  77]
 [ 78  79  80   0   0   0   0   0  86  87  88]
 [ 89  90  91   0   0   0   0   0  97  98  99]
 [100 101 102 103 104 105 106 107 108 109 110]
 [111 112 113 114 115 116 117 118 119 120 121]]


# Stacking together different arrays

In [41]:
a = np.floor(10*np.random.random((3,3)))
a

array([[6., 1., 1.],
       [9., 7., 0.],
       [3., 4., 7.]])

In [42]:
b = np.floor(10*np.random.random((2,3)))
b

array([[2., 1., 0.],
       [4., 6., 0.]])

In [43]:
np.vstack((a,b))

array([[6., 1., 1.],
       [9., 7., 0.],
       [3., 4., 7.],
       [2., 1., 0.],
       [4., 6., 0.]])

In [44]:
c = np.floor(10*np.random.random((3,3)))
c
np.hstack((a,c))

array([[6., 1., 1., 9., 4., 2.],
       [9., 7., 0., 0., 1., 9.],
       [3., 4., 7., 6., 5., 6.]])

# Splitting one array into several

In [45]:
a = np.floor(10*np.random.random((3,12)))
a

array([[4., 7., 0., 5., 1., 1., 3., 0., 0., 3., 9., 1.],
       [0., 7., 8., 3., 4., 6., 0., 9., 8., 2., 0., 9.],
       [5., 5., 6., 6., 9., 9., 8., 6., 8., 6., 5., 1.]])

In [46]:
np.hsplit(a,3)

[array([[4., 7., 0., 5.],
        [0., 7., 8., 3.],
        [5., 5., 6., 6.]]), array([[1., 1., 3., 0.],
        [4., 6., 0., 9.],
        [9., 9., 8., 6.]]), array([[0., 3., 9., 1.],
        [8., 2., 0., 9.],
        [8., 6., 5., 1.]])]

In [47]:
np.vsplit(a,3)

[array([[4., 7., 0., 5., 1., 1., 3., 0., 0., 3., 9., 1.]]),
 array([[0., 7., 8., 3., 4., 6., 0., 9., 8., 2., 0., 9.]]),
 array([[5., 5., 6., 6., 9., 9., 8., 6., 8., 6., 5., 1.]])]

# Linear Algebra

In [48]:
a = np.array([[3.0, 2.0], [4.0, 6.5]])
print(a)

[[3.  2. ]
 [4.  6.5]]


In [49]:
a.transpose()

array([[3. , 4. ],
       [2. , 6.5]])

In [50]:
np.linalg.inv(a)  #linalg is the package in numpy for Linear algebra operations

array([[ 0.56521739, -0.17391304],
       [-0.34782609,  0.26086957]])

In [51]:
u = np.eye(5) #pronounced as I (Identity matrix)
u

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [52]:
print(dir(np.linalg))

['LinAlgError', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '_umath_linalg', 'absolute_import', 'cholesky', 'cond', 'det', 'division', 'eig', 'eigh', 'eigvals', 'eigvalsh', 'info', 'inv', 'lapack_lite', 'linalg', 'lstsq', 'matrix_power', 'matrix_rank', 'multi_dot', 'norm', 'pinv', 'print_function', 'qr', 'slogdet', 'solve', 'svd', 'tensorinv', 'tensorsolve', 'test']


# Pandas

In [53]:
import pandas as pd

In [54]:
print(dir(pd))

['Categorical', 'CategoricalDtype', 'CategoricalIndex', 'DataFrame', 'DateOffset', 'DatetimeIndex', 'DatetimeTZDtype', 'ExcelFile', 'ExcelWriter', 'Float64Index', 'Grouper', 'HDFStore', 'Index', 'IndexSlice', 'Int16Dtype', 'Int32Dtype', 'Int64Dtype', 'Int64Index', 'Int8Dtype', 'Interval', 'IntervalDtype', 'IntervalIndex', 'MultiIndex', 'NaT', 'Panel', 'Period', 'PeriodDtype', 'PeriodIndex', 'RangeIndex', 'Series', 'SparseArray', 'SparseDataFrame', 'SparseDtype', 'SparseSeries', 'TimeGrouper', 'Timedelta', 'TimedeltaIndex', 'Timestamp', 'UInt16Dtype', 'UInt32Dtype', 'UInt64Dtype', 'UInt64Index', 'UInt8Dtype', '__builtins__', '__cached__', '__doc__', '__docformat__', '__file__', '__git_version__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_hashtable', '_lib', '_libs', '_np_version_under1p13', '_np_version_under1p14', '_np_version_under1p15', '_np_version_under1p16', '_np_version_under1p17', '_tslib', '_version', 'api', 'array', 'arrays', 'bdate_rang

# Understanding series and dataframe

In [55]:
series_01 = pd.Series(data =[1,2,3,4,5],index=['a','b','c','d','e'],name= 'My Sample Data',dtype = float)
series_01

a    1.0
b    2.0
c    3.0
d    4.0
e    5.0
Name: My Sample Data, dtype: float64

In [56]:
series_02 = pd.Series(data=[9,8,7,6,5], index=list('abcde'))
series_02

a    9
b    8
c    7
d    6
e    5
dtype: int64

In [57]:
df = pd.DataFrame({'A':series_01, 'B':series_02})
df
print(type(df.A))

<class 'pandas.core.series.Series'>


In [58]:
import numpy as np
# create a random 10 x 10 dataframe
df_01 = pd.DataFrame(data=np.random.randint(1,10,size=(10,10)),index=list('ABCDEFGHIJ'),columns=list('abcdefghij'))
df_01


a  b  c  d  e  f  g  h  i  j
A  3  5  3  1  1  8  2  3  2  3
B  7  1  8  2  3  9  7  4  5  2
C  8  4  9  5  9  4  5  9  8  3
D  1  3  4  2  1  7  8  7  5  1
E  7  7  9  3  9  1  1  4  9  6
F  3  1  4  9  3  9  7  4  3  5
G  5  3  9  4  5  4  5  7  9  7
H  5  7  5  3  7  2  9  1  6  7
I  8  9  2  2  5  5  6  3  8  1
J  6  4  1  7  9  4  4  6  3  6

In [59]:
print(type(df_01))

<class 'pandas.core.frame.DataFrame'>


In [60]:
df = pd.read_csv('housing.csv')

print(type(df))

<class 'pandas.core.frame.DataFrame'>


In [61]:
df.head(10)

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                41.0        880.0           129.0   
1    -122.22     37.86                21.0       7099.0          1106.0   
2    -122.24     37.85                52.0       1467.0           190.0   
3    -122.25     37.85                52.0       1274.0           235.0   
4    -122.25     37.85                52.0       1627.0           280.0   
5    -122.25     37.85                52.0        919.0           213.0   
6    -122.25     37.84                52.0       2535.0           489.0   
7    -122.25     37.84                52.0       3104.0           687.0   
8    -122.26     37.84                42.0       2555.0           665.0   
9    -122.25     37.84                52.0       3549.0           707.0   

   population  households  median_income  median_house_value ocean_proximity  
0       322.0       126.0         8.3252            452600.0        NEAR BAY  
1      2401.0      1138.0         8.3014            358500.0        NEAR BAY  
2       496.0       177.0         7.2574            352100.0        NEAR BAY  
3       558.0       219.0         5.6431            341300.0        NEAR BAY  
4       565.0       259.0         3.8462            342200.0        NEAR BAY  
5       413.0       193.0         4.0368            269700.0        NEAR BAY  
6      1094.0       514.0         3.6591            299200.0        NEAR BAY  
7      1157.0       647.0         3.1200            241400.0        NEAR BAY  
8      1206.0       595.0         2.0804            226700.0        NEAR BAY  
9      1551.0       714.0         3.6912            261100.0        NEAR BAY

In [62]:
df.tail(10)

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
20630    -121.32     39.29                11.0       2640.0           505.0   
20631    -121.40     39.33                15.0       2655.0           493.0   
20632    -121.45     39.26                15.0       2319.0           416.0   
20633    -121.53     39.19                27.0       2080.0           412.0   
20634    -121.56     39.27                28.0       2332.0           395.0   
20635    -121.09     39.48                25.0       1665.0           374.0   
20636    -121.21     39.49                18.0        697.0           150.0   
20637    -121.22     39.43                17.0       2254.0           485.0   
20638    -121.32     39.43                18.0       1860.0           409.0   
20639    -121.24     39.37                16.0       2785.0           616.0   

       population  households  median_income  median_house_value  \
20630      1257.0       445.0         3.5673            112000.0   
20631      1200.0       432.0         3.5179            107200.0   
20632      1047.0       385.0         3.1250            115600.0   
20633      1082.0       382.0         2.5495             98300.0   
20634      1041.0       344.0         3.7125            116800.0   
20635       845.0       330.0         1.5603             78100.0   
20636       356.0       114.0         2.5568             77100.0   
20637      1007.0       433.0         1.7000             92300.0   
20638       741.0       349.0         1.8672             84700.0   
20639      1387.0       530.0         2.3886             89400.0   

      ocean_proximity  
20630          INLAND  
20631          INLAND  
20632          INLAND  
20633          INLAND  
20634          INLAND  
20635          INLAND  
20636          INLAND  
20637          INLAND  
20638          INLAND  
20639          INLAND

In [63]:
df.describe()

longitude      latitude  housing_median_age   total_rooms  \
count  20640.000000  20640.000000        20640.000000  20640.000000   
mean    -119.569704     35.631861           28.639486   2635.763081   
std        2.003532      2.135952           12.585558   2181.615252   
min     -124.350000     32.540000            1.000000      2.000000   
25%     -121.800000     33.930000           18.000000   1447.750000   
50%     -118.490000     34.260000           29.000000   2127.000000   
75%     -118.010000     37.710000           37.000000   3148.000000   
max     -114.310000     41.950000           52.000000  39320.000000   

       total_bedrooms    population    households  median_income  \
count    20433.000000  20640.000000  20640.000000   20640.000000   
mean       537.870553   1425.476744    499.539680       3.870671   
std        421.385070   1132.462122    382.329753       1.899822   
min          1.000000      3.000000      1.000000       0.499900   
25%        296.000000    787.000000    280.000000       2.563400   
50%        435.000000   1166.000000    409.000000       3.534800   
75%        647.000000   1725.000000    605.000000       4.743250   
max       6445.000000  35682.000000   6082.000000      15.000100   

       median_house_value  
count        20640.000000  
mean        206855.816909  
std         115395.615874  
min          14999.000000  
25%         119600.000000  
50%         179700.000000  
75%         264725.000000  
max         500001.000000

In [64]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 10 columns):
longitude             20640 non-null float64
latitude              20640 non-null float64
housing_median_age    20640 non-null float64
total_rooms           20640 non-null float64
total_bedrooms        20433 non-null float64
population            20640 non-null float64
households            20640 non-null float64
median_income         20640 non-null float64
median_house_value    20640 non-null float64
ocean_proximity       20640 non-null object
dtypes: float64(9), object(1)
memory usage: 1.6+ MB


In [65]:
df.median_income.value_counts() #can do value_counts() for one single coulmn

3.1250     49
15.0001    49
2.8750     46
4.1250     44
2.6250     44
3.8750     41
3.0000     38
3.3750     38
3.6250     37
4.0000     37
4.3750     35
2.1250     33
2.3750     32
4.6250     31
3.5000     30
3.2500     29
3.7500     29
4.8750     29
1.6250     29
2.2500     29
4.2500     28
2.5000     28
3.6875     26
2.7500     25
4.5000     24
2.5625     21
1.8750     21
5.0000     20
3.0625     19
4.4375     18
           ..
5.7780      1
1.3672      1
4.6420      1
2.5389      1
6.2113      1
2.1975      1
6.0591      1
2.1403      1
1.5161      1
4.0037      1
1.9306      1
4.0517      1
3.5082      1
5.2649      1
6.7744      1
4.0677      1
2.1216      1
4.1449      1
6.0808      1
5.6263      1
4.8283      1
2.5599      1
7.3031      1
2.7209      1
2.1630      1
4.1514      1
1.2614      1
2.0294      1
6.7079      1
3.7306      1
Name: median_income, Length: 12928, dtype: int64

In [66]:
df.median_income

0        8.3252
1        8.3014
2        7.2574
3        5.6431
4        3.8462
5        4.0368
6        3.6591
7        3.1200
8        2.0804
9        3.6912
10       3.2031
11       3.2705
12       3.0750
13       2.6736
14       1.9167
15       2.1250
16       2.7750
17       2.1202
18       1.9911
19       2.6033
20       1.3578
21       1.7135
22       1.7250
23       2.1806
24       2.6000
25       2.4038
26       2.4597
27       1.8080
28       1.6424
29       1.6875
          ...  
20610    1.3631
20611    1.2857
20612    1.4934
20613    1.4958
20614    2.4695
20615    2.3598
20616    2.0469
20617    3.3021
20618    2.2500
20619    2.7303
20620    4.5625
20621    2.3661
20622    2.4167
20623    2.8235
20624    3.0739
20625    4.1250
20626    2.1667
20627    3.0000
20628    2.5952
20629    2.0943
20630    3.5673
20631    3.5179
20632    3.1250
20633    2.5495
20634    3.7125
20635    1.5603
20636    2.5568
20637    1.7000
20638    1.8672
20639    2.3886
Name: median_income, Len

In [67]:
df.median_income.head(5)

0    8.3252
1    8.3014
2    7.2574
3    5.6431
4    3.8462
Name: median_income, dtype: float64

In [68]:
df.median_income.tail(5)

20635    1.5603
20636    2.5568
20637    1.7000
20638    1.8672
20639    2.3886
Name: median_income, dtype: float64

In [69]:
print(df.median_income.max())
print(df.median_income.min())
print(df['median_income'].mean())
df['median_income'].isna().value_counts()

15.0001
0.4999
3.8706710029070246


False    20640
Name: median_income, dtype: int64

# Acessing Subset of Data - rows,columns,filter

In [70]:
df.columns

Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income',
       'median_house_value', 'ocean_proximity'],
      dtype='object')

In [71]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 10 columns):
longitude             20640 non-null float64
latitude              20640 non-null float64
housing_median_age    20640 non-null float64
total_rooms           20640 non-null float64
total_bedrooms        20433 non-null float64
population            20640 non-null float64
households            20640 non-null float64
median_income         20640 non-null float64
median_house_value    20640 non-null float64
ocean_proximity       20640 non-null object
dtypes: float64(9), object(1)
memory usage: 1.6+ MB


In [72]:
cat_cols_data = df.select_dtypes('float64')
cat_cols_data.head(5)

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                41.0        880.0           129.0   
1    -122.22     37.86                21.0       7099.0          1106.0   
2    -122.24     37.85                52.0       1467.0           190.0   
3    -122.25     37.85                52.0       1274.0           235.0   
4    -122.25     37.85                52.0       1627.0           280.0   

   population  households  median_income  median_house_value  
0       322.0       126.0         8.3252            452600.0  
1      2401.0      1138.0         8.3014            358500.0  
2       496.0       177.0         7.2574            352100.0  
3       558.0       219.0         5.6431            341300.0  
4       565.0       259.0         3.8462            342200.0

In [73]:
df[['longitude','latitude','housing_median_age']].head(5)

longitude  latitude  housing_median_age
0    -122.23     37.88                41.0
1    -122.22     37.86                21.0
2    -122.24     37.85                52.0
3    -122.25     37.85                52.0
4    -122.25     37.85                52.0

In [74]:
df['housing_median_age'][:5]

0    41.0
1    21.0
2    52.0
3    52.0
4    52.0
Name: housing_median_age, dtype: float64

In [75]:
df[['housing_median_age','total_rooms','total_bedrooms']][40:55]

housing_median_age  total_rooms  total_bedrooms
40                52.0       1665.0           419.0
41                51.0        936.0           311.0
42                49.0        713.0           202.0
43                52.0        950.0           202.0
44                52.0       1443.0           311.0
45                52.0       1656.0           420.0
46                50.0       1125.0           322.0
47                43.0       1007.0           312.0
48                40.0        624.0           195.0
49                40.0        946.0           375.0
50                21.0        896.0           453.0
51                43.0       1868.0           456.0
52                41.0       3221.0           853.0
53                52.0       1630.0           456.0
54                52.0       1170.0           235.0

In [76]:
df.loc[2:3]

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
2    -122.24     37.85                52.0       1467.0           190.0   
3    -122.25     37.85                52.0       1274.0           235.0   

   population  households  median_income  median_house_value ocean_proximity  
2       496.0       177.0         7.2574            352100.0        NEAR BAY  
3       558.0       219.0         5.6431            341300.0        NEAR BAY

In [77]:
df.loc[2]

longitude              -122.24
latitude                 37.85
housing_median_age          52
total_rooms               1467
total_bedrooms             190
population                 496
households                 177
median_income           7.2574
median_house_value      352100
ocean_proximity       NEAR BAY
Name: 2, dtype: object

In [78]:
df.iloc[2:3]

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
2    -122.24     37.85                52.0       1467.0           190.0   

   population  households  median_income  median_house_value ocean_proximity  
2       496.0       177.0         7.2574            352100.0        NEAR BAY

In [79]:
df[df['total_rooms']<1467.0].size

53020

In [80]:
df[(df['total_rooms']>=1467.0) & (df['total_bedrooms']<190.0)]

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
4606     -118.33     34.07                52.0       1482.0           171.0   
5249     -118.45     34.08                52.0       1500.0           176.0   
5260     -118.50     34.05                39.0       1487.0           163.0   
10458    -117.65     33.48                 6.0       1638.0           188.0   
14928    -117.02     32.67                20.0       1505.0           184.0   
17854    -121.89     37.46                 5.0       1519.0           186.0   
18354    -122.11     37.36                34.0       1575.0           183.0   
18360    -122.09     37.35                30.0       1502.0           186.0   
19147    -122.69     38.35                12.0       1550.0           187.0   
20501    -118.71     34.30                20.0       1586.0           187.0   

       population  households  median_income  median_house_value  \
4606        531.0       161.0        15.0001            500001.0   
5249        384.0       145.0         7.1576            500001.0   
5260        414.0       160.0        15.0000            500001.0   
10458       572.0       174.0        13.0502            500001.0   
14928       635.0       182.0         6.5772            245200.0   
17854       705.0       186.0        10.3798            500001.0   
18354       511.0       180.0        13.1867            500001.0   
18360       501.0       180.0        10.0259            500001.0   
19147       685.0       188.0         7.2260            255300.0   
20501       699.0       209.0         6.5483            335000.0   

      ocean_proximity  
4606        <1H OCEAN  
5249        <1H OCEAN  
5260        <1H OCEAN  
10458       <1H OCEAN  
14928      NEAR OCEAN  
17854       <1H OCEAN  
18354        NEAR BAY  
18360        NEAR BAY  
19147       <1H OCEAN  
20501       <1H OCEAN

In [81]:
df.loc[1] = [np.nan]*len(df.columns)

In [82]:
df.head(5)

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                41.0        880.0           129.0   
1        NaN       NaN                 NaN          NaN             NaN   
2    -122.24     37.85                52.0       1467.0           190.0   
3    -122.25     37.85                52.0       1274.0           235.0   
4    -122.25     37.85                52.0       1627.0           280.0   

   population  households  median_income  median_house_value ocean_proximity  
0       322.0       126.0         8.3252            452600.0        NEAR BAY  
1         NaN         NaN            NaN                 NaN             NaN  
2       496.0       177.0         7.2574            352100.0        NEAR BAY  
3       558.0       219.0         5.6431            341300.0        NEAR BAY  
4       565.0       259.0         3.8462            342200.0        NEAR BAY

In [83]:
df['population'].isnull()

0        False
1         True
2        False
3        False
4        False
5        False
6        False
7        False
8        False
9        False
10       False
11       False
12       False
13       False
14       False
15       False
16       False
17       False
18       False
19       False
20       False
21       False
22       False
23       False
24       False
25       False
26       False
27       False
28       False
29       False
         ...  
20610    False
20611    False
20612    False
20613    False
20614    False
20615    False
20616    False
20617    False
20618    False
20619    False
20620    False
20621    False
20622    False
20623    False
20624    False
20625    False
20626    False
20627    False
20628    False
20629    False
20630    False
20631    False
20632    False
20633    False
20634    False
20635    False
20636    False
20637    False
20638    False
20639    False
Name: population, Length: 20640, dtype: bool

# Droping rows and columns

In [84]:
df.drop(['ocean_proximity'],axis=1)

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -122.23     37.88                41.0        880.0           129.0   
1            NaN       NaN                 NaN          NaN             NaN   
2        -122.24     37.85                52.0       1467.0           190.0   
3        -122.25     37.85                52.0       1274.0           235.0   
4        -122.25     37.85                52.0       1627.0           280.0   
5        -122.25     37.85                52.0        919.0           213.0   
6        -122.25     37.84                52.0       2535.0           489.0   
7        -122.25     37.84                52.0       3104.0           687.0   
8        -122.26     37.84                42.0       2555.0           665.0   
9        -122.25     37.84                52.0       3549.0           707.0   
10       -122.26     37.85                52.0       2202.0           434.0   
11       -122.26     37.85                52.0       3503.0           752.0   
12       -122.26     37.85                52.0       2491.0           474.0   
13       -122.26     37.84                52.0        696.0           191.0   
14       -122.26     37.85                52.0       2643.0           626.0   
15       -122.26     37.85                50.0       1120.0           283.0   
16       -122.27     37.85                52.0       1966.0           347.0   
17       -122.27     37.85                52.0       1228.0           293.0   
18       -122.26     37.84                50.0       2239.0           455.0   
19       -122.27     37.84                52.0       1503.0           298.0   
20       -122.27     37.85                40.0        751.0           184.0   
21       -122.27     37.85                42.0       1639.0           367.0   
22       -122.27     37.84                52.0       2436.0           541.0   
23       -122.27     37.84                52.0       1688.0           337.0   
24       -122.27     37.84                52.0       2224.0           437.0   
25       -122.28     37.85                41.0        535.0           123.0   
26       -122.28     37.85                49.0       1130.0           244.0   
27       -122.28     37.85                52.0       1898.0           421.0   
28       -122.28     37.84                50.0       2082.0           492.0   
29       -122.28     37.84                52.0        729.0           160.0   
...          ...       ...                 ...          ...             ...   
20610    -121.56     39.10                28.0       2130.0           484.0   
20611    -121.55     39.10                27.0       1783.0           441.0   
20612    -121.56     39.08                26.0       1377.0           289.0   
20613    -121.55     39.09                31.0       1728.0           365.0   
20614    -121.54     39.08                26.0       2276.0           460.0   
20615    -121.54     39.08                23.0       1076.0           216.0   
20616    -121.53     39.08                15.0       1810.0           441.0   
20617    -121.53     39.06                20.0        561.0           109.0   
20618    -121.55     39.06                25.0       1332.0           247.0   
20619    -121.56     39.01                22.0       1891.0           340.0   
20620    -121.48     39.05                40.0        198.0            41.0   
20621    -121.47     39.01                37.0       1244.0           247.0   
20622    -121.44     39.00                20.0        755.0           147.0   
20623    -121.37     39.03                32.0       1158.0           244.0   
20624    -121.41     39.04                16.0       1698.0           300.0   
20625    -121.52     39.12                37.0        102.0            17.0   
20626    -121.43     39.18                36.0       1124.0           184.0   
20627    -121.32     39.13                 5.0        358.0            65.0   
20628    -121.48     39.10                19.0       2043

In [85]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 10 columns):
longitude             20639 non-null float64
latitude              20639 non-null float64
housing_median_age    20639 non-null float64
total_rooms           20639 non-null float64
total_bedrooms        20432 non-null float64
population            20639 non-null float64
households            20639 non-null float64
median_income         20639 non-null float64
median_house_value    20639 non-null float64
ocean_proximity       20639 non-null object
dtypes: float64(9), object(1)
memory usage: 1.6+ MB


In [86]:
df.dropna().info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 20432 entries, 0 to 20639
Data columns (total 10 columns):
longitude             20432 non-null float64
latitude              20432 non-null float64
housing_median_age    20432 non-null float64
total_rooms           20432 non-null float64
total_bedrooms        20432 non-null float64
population            20432 non-null float64
households            20432 non-null float64
median_income         20432 non-null float64
median_house_value    20432 non-null float64
ocean_proximity       20432 non-null object
dtypes: float64(9), object(1)
memory usage: 1.7+ MB


In [88]:
df1=pd.read_csv('titanic_dataset.csv')
df1.head(5)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [89]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
PassengerId    891 non-null int64
Survived       891 non-null int64
Pclass         891 non-null int64
Name           891 non-null object
Sex            891 non-null object
Age            714 non-null float64
SibSp          891 non-null int64
Parch          891 non-null int64
Ticket         891 non-null object
Fare           891 non-null float64
Cabin          204 non-null object
Embarked       889 non-null object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.6+ KB


In [90]:
df1.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [91]:
df1.columns.notnull()

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True])

In [92]:
df1.Cabin.isna()

0       True
1      False
2       True
3      False
4       True
5       True
6      False
7       True
8       True
9       True
10     False
11     False
12      True
13      True
14      True
15      True
16      True
17      True
18      True
19      True
20      True
21     False
22      True
23     False
24      True
25      True
26      True
27     False
28      True
29      True
       ...  
861     True
862    False
863     True
864     True
865     True
866     True
867    False
868     True
869     True
870     True
871    False
872    False
873     True
874     True
875     True
876     True
877     True
878     True
879    False
880     True
881     True
882     True
883     True
884     True
885     True
886     True
887    False
888     True
889    False
890     True
Name: Cabin, Length: 891, dtype: bool

In [93]:
df1['Cabin'].isnull().sum()


687

In [ ]:
df1.isnull().sum(axis=0)

# Function Application
Map for transforming one column to another

Can be applied only to series

In [94]:
titanic_data_age = df1[df1.Age.notnull()]
titanic_data_age

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
6              7         0       1   
7              8         0       3   
8              9         1       3   
9             10         1       2   
10            11         1       3   
11            12         1       1   
12            13         0       3   
13            14         0       3   
14            15         0       3   
15            16         1       2   
16            17         0       3   
18            19         0       3   
20            21         0       2   
21            22         1       2   
22            23         1       3   
23            24         1       1   
24            25         0       3   
25            26         1       3   
27            28         0       1   
30            31         0       1   
33            34         0       2   
34            35         0       1   
35            36         0       1   
37            38         0       3   
38            39         0       3   
..           ...       ...     ...   
856          857         1       1   
857          858         1       1   
858          859         1       3   
860          861         0       3   
861          862         0       2   
862          863         1       1   
864          865         0       2   
865          866         1       2   
866          867         1       2   
867          868         0       1   
869          870         1       3   
870          871         0       3   
871          872         1       1   
872          873         0       1   
873          874         0       3   
874          875         1       2   
875          876         1       3   
876          877         0       3   
877          878         0       3   
879          880         1       1   
880          881         1       2   
881          882         0       3   
882          883         0       3   
883          884         0       2   
884          885         0       3   
885          886         0       3   
886          887         0       2   
887          888         1       1   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
6                              McCarthy, Mr. Timothy J    male  54.0      0   
7                       Palsson, Master. Gosta Leonard    male   2.0      3   
8    Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0   
9                  Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1   
10                     Sandstrom, Miss. Marguerite Rut  female   4.0      1   
11                            Bonnell, Miss. Elizabeth  female  58.0      0   
12                      Saundercock, Mr. William Henry    male  20.0      0   
13                         Andersson, Mr. Anders Johan    male  39.0      1   
14                Vestrom, Miss. Hulda Amanda Adolfina  female  14.0      0   
15                    Hewlett, Mrs. (Mary D Kingcome)   female  55.0      0   
16                                Rice, Master. Eugene    male   2.0      4   
18   Vander Planke, Mrs. Julius (Emelia Maria Vande...  female  31.0      1   
20                                Fynney, Mr. Joseph J    male  35.0      0   
21                               Beesley, Mr. Lawrence    male  34.0      0   
22                         McGowan, Miss. Anna "Annie"  female  15.0

In [95]:
titanic_data_age.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 714 entries, 0 to 890
Data columns (total 12 columns):
PassengerId    714 non-null int64
Survived       714 non-null int64
Pclass         714 non-null int64
Name           714 non-null object
Sex            714 non-null object
Age            714 non-null float64
SibSp          714 non-null int64
Parch          714 non-null int64
Ticket         714 non-null object
Fare           714 non-null float64
Cabin          185 non-null object
Embarked       712 non-null object
dtypes: float64(2), int64(5), object(5)
memory usage: 72.5+ KB


In [ ]:
df1['age_category'] = df1.Age.map(lambda age:'kid' if age<18 else 'adult' )

In [ ]:
df1.head(10)

In [ ]:
df1.Age.apply('sum')

In [ ]:
titanic_data_age.Age.apply('sum')

In [ ]:
titanic_data_age.Age.apply(lambda age:'kid' if age<18 else 'adult')

In [ ]:
titanic_data_age

In [ ]:
df1[df1.Name.str.contains('Mrs.')].head()

In [ ]:
df1[df1['SibSp']==1]

# Append , Merge, Join & Concatenate
Append for stacking dataframe

In [ ]:
df2 = pd.DataFrame(data=np.random.randint(1,10,size=(10,3)), columns=list('ABC'))
df2

In [ ]:
df3 = pd.DataFrame(data=np.random.randint(1,10,size=(10,3)), columns=list('ABC'))
df3

In [ ]:
df2.append(df3, ignore_index=True)